### ISSUE TITLE
assertions in test-initial-config.py are bad

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns-sysrepo#20]
1. `assert` is not a function, so we shouldn't be using `()` (notably this destroys tests that specify a custom exception message, such as the one in #15)
2. we should use the assertions from nose?

**Comment by pieterlexis** [comment]
> we should use the assertions from nose?

Perhaps we should use the built-in unittest assertions: https://docs.python.org/3.6/library/unittest.html#basic-example

**Comment by Habbie** [comment]
> Perhaps we should use the built-in unittest assertions: https://docs.python.org/3.6/library/unittest.html#basic-example

ah, I guess i meant those, yes :)
