### ISSUE TITLE
Unable to create wildcards rrsets

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns-sysrepo#5]
This seems to be a shortcoming in the YANG model. The `inet:domain-name` regex should be expanded.

**Comment by Habbie** [comment]
How about an `is-wildcard` flag on an RRset instead? It would avoid making the regex even worse.

**Comment by pieterlexis** [comment]
But then the owner name would not be 'correct'.

The auth would send the `*.XXXX` owner name. So we'd need to parse that out (not impossible)
